/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32h723xx.h"

#define                 LED_GREEN_PORT                                  GPIOB
#define                 LED_GREEN_PIN                                   0UL
#define                 LED_RED_PORT                                    GPIOB
#define                 LED_RED_PIN                                     14UL
#define                 LED_YELLOW_PORT                                 GPIOE
#define                 LED_YELLOW_PIN                                  1UL

#define                 BUTTON_USER_PORT                                GPIOC
#define                 BUTTON_USER_PIN                                 13UL

#define                 ADC1_INP2_PORT                                  GPIOF
#define                 ADC1_INP2_PIN                                   11UL

#define                 ADC1_INP3_PORT                                  GPIOA
#define                 ADC1_INP3_PIN                                   6UL

int main(void)
{
    // ====================================================================================================
    PWR->CR3 |= PWR_CR3_LDOEN;
    while(!(PWR->CSR1 & PWR_CSR1_ACTVOSRDY));
    PWR->D3CR &= ~PWR_D3CR_VOS;
    while(!(PWR->D3CR & PWR_D3CR_VOSRDY));
    // ====================================================================================================
    FLASH->ACR &= ~(FLASH_ACR_LATENCY | FLASH_ACR_WRHIGHFREQ);
    FLASH->ACR |= FLASH_ACR_LATENCY_3WS | (0x3U << FLASH_ACR_WRHIGHFREQ_Pos);
    // ====================================================================================================
    RCC->CR |= RCC_CR_HSEON | RCC_CR_HSEBYP;
    while(!(RCC->CR & RCC_CR_HSERDY));

    RCC->PLLCKSELR &= ~(RCC_PLLCKSELR_DIVM1 | RCC_PLLCKSELR_PLLSRC);
    RCC->PLLCKSELR |= 0x2UL << RCC_PLLCKSELR_PLLSRC_Pos |
                      4UL << RCC_PLLCKSELR_DIVM1_Pos;

    RCC->PLLCFGR &= ~(RCC_PLLCFGR_PLL1FRACEN | RCC_PLLCFGR_PLL1VCOSEL | RCC_PLLCFGR_PLL1RGE | RCC_PLLCFGR_DIVQ1EN | RCC_PLLCFGR_DIVR1EN);
    RCC->PLLCFGR |= RCC_PLLCFGR_PLL1RGE_1 | RCC_PLLCFGR_DIVP1EN;

    RCC->PLL1DIVR = 0x0U;
    RCC->PLL1DIVR |= ((275UL - 1UL) << RCC_PLL1DIVR_N1_Pos) |
                     ((1UL - 1UL) << RCC_PLL1DIVR_P1_Pos) |
                     RCC_PLL1DIVR_Q1 |
                     RCC_PLL1DIVR_R1;

    RCC->D1CFGR &= ~(RCC_D1CFGR_HPRE | RCC_D1CFGR_D1PPRE | RCC_D1CFGR_D1CPRE);
    RCC->D1CFGR |= 0x8UL << RCC_D1CFGR_HPRE_Pos |
                   0x4UL << RCC_D1CFGR_D1PPRE_Pos |
                   0x0UL << RCC_D1CFGR_D1CPRE_Pos;

    RCC->D2CFGR &= ~(RCC_D2CFGR_D2PPRE1 | RCC_D2CFGR_D2PPRE2);
    RCC->D2CFGR |= 0x4UL << RCC_D2CFGR_D2PPRE1_Pos |
                   0x4UL << RCC_D2CFGR_D2PPRE2_Pos;

    RCC->D3CFGR &= ~(RCC_D3CFGR_D3PPRE);
    RCC->D3CFGR |= 0x4UL << RCC_D3CFGR_D3PPRE_Pos;

    RCC->CR |= RCC_CR_PLL1ON;
    while(!(RCC->CR & RCC_CR_PLL1RDY));
    RCC->CFGR &= ~RCC_CFGR_SW;
    RCC->CFGR |= RCC_CFGR_SW_PLL1;
    while((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_PLL1);
    // ====================================================================================================
    // PLL2 for ADC
    // RCC->PLLCKSELR &= ~RCC_PLLCKSELR_DIVM2;
    // RCC->PLLCKSELR |= 4UL << RCC_PLLCKSELR_DIVM2_Pos;

    // RCC->PLLCFGR &= ~(RCC_PLLCFGR_PLL2FRACEN | RCC_PLLCFGR_PLL2VCOSEL | RCC_PLLCFGR_PLL2RGE | RCC_PLLCFGR_DIVQ2EN | RCC_PLLCFGR_DIVR2EN);
    // RCC->PLLCFGR |= RCC_PLLCFGR_PLL2RGE_1 | RCC_PLLCFGR_DIVP2EN;

    // RCC->PLL2DIVR = 0x0U;
    // RCC->PLL2DIVR |= ((320UL - 1UL) << RCC_PLL2DIVR_N2_Pos) |
    //                  ((1UL - 1UL) << RCC_PLL2DIVR_P2_Pos) |
    //                  RCC_PLL2DIVR_Q2 |
    //                  RCC_PLL2DIVR_R2;

    // RCC->CR |= RCC_CR_PLL2ON;
    // while(!(RCC->CR & RCC_CR_PLL2RDY));
    // ====================================================================================================
    SCB->CPACR |= ((3UL << 10 * 2) | (3UL << 11 * 2));
    // ====================================================================================================
    RCC->APB1LENR |= RCC_APB1LENR_TIM6EN;
    TIM6->PSC = 27500UL - 1UL;
    TIM6->ARR = 10000UL - 1UL;
    TIM6->CR1 |= TIM_CR1_ARPE;
    TIM6->DIER |= TIM_DIER_UIE;
    NVIC_EnableIRQ(TIM6_DAC_IRQn);
    TIM6->CR1 |= TIM_CR1_CEN;
    // ====================================================================================================
    RCC->AHB4ENR |= RCC_AHB4ENR_GPIOBEN;

    LED_GREEN_PORT->MODER &= ~(0x3UL << (LED_GREEN_PIN * 2));
    LED_GREEN_PORT->MODER |= 0x1UL << (LED_GREEN_PIN * 2);

    RCC->AHB4ENR |= RCC_AHB4ENR_GPIOBEN;

    LED_RED_PORT->MODER &= ~(0x3UL << (LED_RED_PIN * 2));
    LED_RED_PORT->MODER |= 0x1UL << (LED_RED_PIN * 2);

    RCC->AHB4ENR |= RCC_AHB4ENR_GPIOEEN;

    LED_YELLOW_PORT->MODER &= ~(0x3UL << (LED_YELLOW_PIN * 2));
    LED_YELLOW_PORT->MODER |= 0x1UL << (LED_YELLOW_PIN * 2);

    RCC->AHB4ENR |= RCC_AHB4ENR_GPIOCEN;

    BUTTON_USER_PORT->MODER &= ~(0x3UL << (BUTTON_USER_PIN * 2));
    // ====================================================================================================
    RCC->AHB4ENR |= RCC_AHB4ENR_GPIOFEN;

    ADC1_INP2_PORT->MODER &= ~(0x3UL << (ADC1_INP2_PIN * 2));
    ADC1_INP2_PORT->MODER |= 0x3UL << (ADC1_INP2_PIN * 2);

    // RCC->AHB4ENR |= RCC_AHB4ENR_GPIOAEN;

    // ADC1_INP3_PORT->MODER &= ~(0x3UL << (ADC1_INP3_PIN * 2));
    // ADC1_INP3_PORT->MODER |= 0x3UL << (ADC1_INP3_PIN * 2));

    RCC->AHB1ENR |= RCC_AHB1ENR_ADC12EN;

    ADC12_COMMON->CCR &= ~(ADC_CCR_CKMODE | ADC_CCR_PRESC);
    ADC12_COMMON->CCR |= 0x1UL << ADC_CCR_CKMODE;

    ADC1->CR &= ~ADC_CR_DEEPPWD;
    ADC1->CR |= ADC_CR_ADVREGEN;
    // for(uint32_t n = 0; n < 10000; n++) __NOP();
    while(!(ADC1->ISR & ADC_ISR_LDORDY)) __NOP();

    ADC1->CR &= ~ADC_CR_ADEN;

    ADC1->CR &= ~ADC_CR_ADCALDIF;
    ADC1->CR |= ADC_CR_ADCALLIN;
    ADC1->CR |= ADC_CR_ADCAL;
    while(ADC1->CR & ADC_CR_ADCAL) __NOP();

    ADC1->ISR |= ADC_ISR_ADRDY;
    ADC1->CR  |= ADC_CR_ADEN;
    while (!(ADC1->ISR & ADC_ISR_ADRDY)) __NOP();

    ADC1->PCSEL_RES0 |= ADC_PCSEL_PCSEL_2;
    // ADC1->PCSEL_RES0 |= ADC_PCSEL_PCSEL_3;

    ADC1->CFGR |= ADC_CFGR_CONT | ADC_CFGR_OVRMOD;

    // TODO configure ADC channels, sampling time, etc.

	for(;;);
}

void TIM6_DAC_IRQHandler(void)
{
    if(TIM6->SR & TIM_SR_UIF)
    {
        TIM6->SR &= ~TIM_SR_UIF;
        
        LED_GREEN_PORT->ODR ^= 1UL << LED_GREEN_PIN;
    }
}
