/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32h723xx.h"

#define                 LED_GREEN_PORT                                  GPIOB
#define                 LED_GREEN_PIN                                   0U
#define                 LED_RED_PORT                                    GPIOB
#define                 LED_RED_PIN                                     14U
#define                 LED_YELLOW_PORT                                 GPIOE
#define                 LED_YELLOW_PIN                                  1U

#define                 BUTTON_USER_PORT                                GPIOC
#define                 BUTTON_USER_PIN                                 13U

int main(void)
{
    // ====================================================================================================
    PWR->CR3 |= PWR_CR3_LDOEN;
    while(!(PWR->CSR1 & PWR_CSR1_ACTVOSRDY));
    PWR->D3CR &= ~PWR_D3CR_VOS;
    while(!(PWR->D3CR & PWR_D3CR_VOSRDY));
    // ====================================================================================================
    FLASH->ACR &= ~(FLASH_ACR_LATENCY | FLASH_ACR_WRHIGHFREQ);
    FLASH->ACR |= FLASH_ACR_LATENCY_3WS | (0x3U << FLASH_ACR_WRHIGHFREQ_Pos);
    // ====================================================================================================
    RCC->CR |= RCC_CR_HSEON | RCC_CR_HSEBYP;
    while(!(RCC->CR & RCC_CR_HSERDY));

    RCC->PLLCKSELR &= ~(RCC_PLLCKSELR_DIVM1 | RCC_PLLCKSELR_PLLSRC);
    RCC->PLLCKSELR |= 0x2UL << RCC_PLLCKSELR_PLLSRC_Pos |
                      4UL << RCC_PLLCKSELR_DIVM1_Pos;

    RCC->PLLCFGR &= ~(RCC_PLLCFGR_PLL1FRACEN | RCC_PLLCFGR_PLL1VCOSEL | RCC_PLLCFGR_PLL1RGE | RCC_PLLCFGR_DIVQ1EN | RCC_PLLCFGR_DIVR1EN);
    RCC->PLLCFGR |= RCC_PLLCFGR_PLL1RGE_1 | RCC_PLLCFGR_DIVP1EN;

    RCC->PLL1DIVR = 0x0U;
    RCC->PLL1DIVR |= ((275UL - 1UL) << RCC_PLL1DIVR_N1_Pos) |
                     ((1UL - 1UL) << RCC_PLL1DIVR_P1_Pos) |
                     RCC_PLL1DIVR_Q1 |
                     RCC_PLL1DIVR_R1;

    RCC->D1CFGR &= ~(RCC_D1CFGR_HPRE | RCC_D1CFGR_D1PPRE | RCC_D1CFGR_D1CPRE);
    RCC->D1CFGR |= 0x8UL << RCC_D1CFGR_HPRE_Pos |
                   0x4UL << RCC_D1CFGR_D1PPRE_Pos |
                   0x0UL << RCC_D1CFGR_D1CPRE_Pos;

    RCC->D2CFGR &= ~(RCC_D2CFGR_D2PPRE1 | RCC_D2CFGR_D2PPRE2);
    RCC->D2CFGR |= 0x4UL << RCC_D2CFGR_D2PPRE1_Pos |
                   0x4UL << RCC_D2CFGR_D2PPRE2_Pos;

    RCC->D3CFGR &= ~(RCC_D3CFGR_D3PPRE);
    RCC->D3CFGR |= 0x4UL << RCC_D3CFGR_D3PPRE_Pos;

    RCC->CR |= RCC_CR_PLL1ON;
            while(!(RCC->CR & RCC_CR_PLL1RDY));
            RCC->CFGR &= ~RCC_CFGR_SW;
            RCC->CFGR |= RCC_CFGR_SW_PLL1;
            while((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_PLL1);
    // ====================================================================================================
    SCB->CPACR |= ((3UL << 10 * 2) | (3UL << 11 * 2));
    // ====================================================================================================
    RCC->APB1LENR |= RCC_APB1LENR_TIM6EN;
    TIM6->PSC = 27500UL - 1UL;
    TIM6->ARR = 10000UL - 1UL;
    TIM6->CR1 |= TIM_CR1_ARPE;
    TIM6->DIER |= TIM_DIER_UIE;
    NVIC_EnableIRQ(TIM6_DAC_IRQn);
    TIM6->CR1 |= TIM_CR1_CEN;
    // ====================================================================================================
    RCC->AHB4ENR |= RCC_AHB4ENR_GPIOBEN;

    LED_GREEN_PORT->MODER &= ~(0x3UL << (LED_GREEN_PIN * 2));
    LED_GREEN_PORT->MODER |= 0x1UL << (LED_GREEN_PIN * 2);

    RCC->AHB4ENR |= RCC_AHB4ENR_GPIOBEN;

    LED_RED_PORT->MODER &= ~(0x3UL << (LED_RED_PIN * 2));
    LED_RED_PORT->MODER |= 0x1UL << (LED_RED_PIN * 2);

    RCC->AHB4ENR |= RCC_AHB4ENR_GPIOEEN;

    LED_YELLOW_PORT->MODER &= ~(0x3UL << (LED_YELLOW_PIN * 2));
    LED_YELLOW_PORT->MODER |= 0x1UL << (LED_YELLOW_PIN * 2);

    RCC->AHB4ENR |= RCC_AHB4ENR_GPIOCEN;

    BUTTON_USER_PORT->MODER &= ~(0x3UL << (BUTTON_USER_PIN * 2));
    // ====================================================================================================

	for(;;);
}

void TIM6_DAC_IRQHandler(void)
{
    if(TIM6->SR & TIM_SR_UIF)
    {
        TIM6->SR &= ~TIM_SR_UIF;
        
        LED_GREEN_PORT->ODR ^= 1UL << LED_GREEN_PIN;
    }
}
