/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "arm_math_types.h"
#include "stm32h723xx.h"
#include "rcc_cfg.h"
#include "adc_cfg.h"
#include "usart_cfg.h"
#include "nanoprintf.h"
#include "my_math.h"


#define                 LED_GREEN_PORT                                  GPIOB
#define                 LED_GREEN_PIN                                   0UL
#define                 LED_RED_PORT                                    GPIOB
#define                 LED_RED_PIN                                     14UL
#define                 LED_YELLOW_PORT                                 GPIOE
#define                 LED_YELLOW_PIN                                  1UL

#define                 BUTTON_USER_PORT                                GPIOC
#define                 BUTTON_USER_PIN                                 13UL

#define                 TIM_REF                                         TIM7
#define                 TIM_REF_PSC                                     27500UL - 1UL
#define                 TIM_REF_ARR                                     10000UL - 1UL
#define                 TIM_REF_IRQn                                    TIM7_IRQn
#define                 TIM_REF_IRQHandler                              TIM7_IRQHandler

// #define                 ADC1_INP2_PORT                                  GPIOF
// #define                 ADC1_INP2_PIN                                   11UL

// #define                 ADC1_INP3_PORT                                  GPIOA
// #define                 ADC1_INP3_PIN                                   6UL

// #define                 ADC1_DMAMUX_INPUT                               9UL
// #define                 ADC1_DMAMUX_CH                                  DMAMUX1_Channel4
// #define                 ADC1_DMA                                        DMA1
// #define                 ADC1_DMA_STREAM                                 DMA1_Stream4

// #define                 CURRENT_SENSOR_PORT                             ADC1_INP2_PORT
// #define                 CURRENT_SENSOR_PIN                              ADC1_INP2_PIN

// #define                 VOLTAGE_SENSOR_PORT                             ADC1_INP3_PORT
// #define                 VOLTAGE_SENSOR_PIN                              ADC1_INP3_PIN

// #define                 SENSORS_ADC                                     ADC1
// #define                 SENSORS_DMAMUX_INPUT                            ADC1_DMAMUX_INPUT
// #define                 SENSORS_DMAMUX_CH                               ADC1_DMAMUX_CH
// #define                 SENSORS_DMA                                     ADC1_DMA
// #define                 SENSORS_DMA_STREAM                              ADC1_DMA_STREAM

#define                 DESC_TIM                                        TIM6
#define                 DESC_TIM_PSC                                    25UL - 1UL
#define                 DESC_TIM_ARR                                    11UL - 1UL
#define                 DESC_TIM_IRQn                                   TIM6_DAC_IRQn
#define                 DESC_TIM_IRQHandler                             TIM6_DAC_IRQHandler

// ====================================================================================================

typedef struct
{
    float current;
    float voltage;
} SensorData_t;

volatile uint32_t cur_conv_time = 0;
volatile uint32_t cur_tran_time = 0;

volatile uint32_t vol_conv_time = 0;
volatile uint32_t vol_tran_time = 0;

// ----------------------------------------------------------------------------------------------------

float32_t R_L   = 1e-3f;                    // Inductor resistance  [Ohms]
float32_t L     = 510e-4f;                  // Inductance           [Henries]
float32_t C     = 5.8e-4f;                  // Capacitance          [Farads]
float32_t f     = 10e3f;                    // Frequency            [Hz]
float32_t V_in  = 13.0f;                    // Input voltage        [V]
float32_t V_out = 5.0f;                     // Output voltage       [V]
float32_t R     = 3.5f;                     // Load resistance      [Ohms]
float32_t mu    = 8e3f;                     // Observer gain        [-]

my_system_t sys;

sys.A.val = { 1.0f, 0.01f, 0.0f, 1.0f };

// ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

int main(void)
{
    // ====================================================================================================
    PWR->CR3 |= PWR_CR3_LDOEN;
    while(!(PWR->CSR1 & PWR_CSR1_ACTVOSRDY))  __NOP();
    PWR->D3CR &= ~PWR_D3CR_VOS;
    while(!(PWR->D3CR & PWR_D3CR_VOSRDY))  __NOP();
    // ====================================================================================================
    FLASH->ACR &= ~(FLASH_ACR_LATENCY | FLASH_ACR_WRHIGHFREQ);
    FLASH->ACR |= FLASH_ACR_LATENCY_3WS | (0x3U << FLASH_ACR_WRHIGHFREQ_Pos);
    // ====================================================================================================
    rcc_init();
    pll2_init();
    // ====================================================================================================
    SCB->CPACR |= ((3UL << 10 * 2) | (3UL << 11 * 2));
    // ====================================================================================================
    RCC->APB1LENR |= RCC_APB1LENR_TIM7EN;
    (void)RCC->APB1LENR;
    TIM_REF->PSC = TIM_REF_PSC;
    TIM_REF->ARR = TIM_REF_ARR;
    TIM_REF->CR1 |= TIM_CR1_ARPE;
    TIM_REF->DIER |= TIM_DIER_UIE;
    NVIC_EnableIRQ(TIM_REF_IRQn);
    TIM_REF->CR1 |= TIM_CR1_CEN;
    // ====================================================================================================
    // RCC->APB1LENR |= RCC_APB1LENR_TIM6EN;
    // TIM6->PSC = 27500UL - 1UL;
    // TIM6->ARR = 10000UL - 1UL;
    // TIM6->CR1 |= TIM_CR1_ARPE;
    // TIM6->DIER |= TIM_DIER_UIE;
    // NVIC_EnableIRQ(TIM6_DAC_IRQn);
    // TIM6->CR1 |= TIM_CR1_CEN;
    // ====================================================================================================
    RCC->AHB4ENR |= RCC_AHB4ENR_GPIOBEN;

    LED_GREEN_PORT->MODER &= ~(0x3UL << (LED_GREEN_PIN * 2));
    LED_GREEN_PORT->MODER |= 0x1UL << (LED_GREEN_PIN * 2);

    RCC->AHB4ENR |= RCC_AHB4ENR_GPIOBEN;

    LED_RED_PORT->MODER &= ~(0x3UL << (LED_RED_PIN * 2));
    LED_RED_PORT->MODER |= 0x1UL << (LED_RED_PIN * 2);

    RCC->AHB4ENR |= RCC_AHB4ENR_GPIOEEN;

    LED_YELLOW_PORT->MODER &= ~(0x3UL << (LED_YELLOW_PIN * 2));
    LED_YELLOW_PORT->MODER |= 0x1UL << (LED_YELLOW_PIN * 2);

    RCC->AHB4ENR |= RCC_AHB4ENR_GPIOCEN;

    BUTTON_USER_PORT->MODER &= ~(0x3UL << (BUTTON_USER_PIN * 2));
    // ====================================================================================================
    cur_sen_adc_init();
    vol_sen_adc_init();
    // ====================================================================================================
    // RCC->AHB4ENR |= RCC_AHB4ENR_GPIODEN;
    // GPIOD->MODER &= ~(0x3UL << (13UL * 2));
    // GPIOD->MODER |= 0x2UL << (13UL * 2);
    // GPIOD->AFR[13UL / 8] &= ~(0xFUL << ((13UL % 8) * 4));
    // GPIOD->AFR[13UL / 8] |= 1UL << ((13UL % 8) * 4);
    
    RCC->CSR |= RCC_CSR_LSION;
    while(!(RCC->CSR & RCC_CSR_LSIRDY))  __NOP();
    
    RCC->D2CCIP2R &= ~RCC_D2CCIP2R_LPTIM1SEL;
    RCC->D2CCIP2R |= 0x4UL << RCC_D2CCIP2R_LPTIM1SEL_Pos;

    RCC->APB1LENR |= RCC_APB1LENR_LPTIM1EN;
    LPTIM1->CFGR |= 0x5UL << LPTIM_CFGR_PRESC_Pos;
    LPTIM1->CR |= LPTIM_CR_ENABLE;
    LPTIM1->ARR = 1024UL - 1UL;
    while(!(LPTIM1->ISR & LPTIM_ISR_ARROK))  __NOP();
    LPTIM1->ICR = LPTIM_ICR_ARROKCF;
    LPTIM1->CMP = LPTIM1->ARR / 2;
    while(!(LPTIM1->ISR & LPTIM_ISR_CMPOK))  __NOP();
    LPTIM1->ICR = LPTIM_ICR_CMPOKCF;
    LPTIM1->ICR = LPTIM_ICR_ARRMCF | LPTIM_ICR_CMPMCF;
    LPTIM1->CR |= LPTIM_CR_CNTSTRT;

    usart3_init();
    // ====================================================================================================
    RCC->APB1LENR |= RCC_APB1LENR_TIM6EN;
    DESC_TIM->PSC = DESC_TIM_PSC;
    DESC_TIM->ARR = DESC_TIM_ARR;
    DESC_TIM->CR1 |= TIM_CR1_ARPE;
    DESC_TIM->CR2 = 2UL << TIM_CR2_MMS_Pos; // Update event as TRGO
    DESC_TIM->DIER |= TIM_DIER_UIE;
    // NVIC_EnableIRQ(DESC_TIM_IRQn);
    DESC_TIM->CR1 |= TIM_CR1_CEN;

    USART3_TX_DMA_STREAM->NDTR = npf_snprintf((char *)usart3_tx_buf, 0xFF, "Current: %u, Voltage: %u\r\n", cur_sen_adc_val, vol_sen_adc_val);
    USART3_TX_DMAMUX_CH->CCR |= npf_snprintf((char *)usart3_tx_buf, 0xFF, "Current: %u, Voltage: %u\r\n", cur_sen_adc_val, vol_sen_adc_val) << DMAMUX_CxCR_NBREQ_Pos;
    USART3_TX_DMA_STREAM->CR |= DMA_SxCR_EN;

    // ====================================================================================================

	for(;;)
    {
        // if (LPTIM3->ISR & LPTIM_ISR_ARRM)
        // {
        //     LPTIM3->ICR |= LPTIM_ICR_ARRMCF;
        // }
        // if (LPTIM3->ISR & LPTIM_ISR_CMPM)
        // {
        //     LPTIM3->ICR |= LPTIM_ICR_CMPMCF;
        // }
        // if (SENSORS_ADC->ISR & ADC_ISR_EOC)
        // {
        //     adc_value = SENSORS_ADC->DR;
        // }
        if (BUTTON_USER_PORT->IDR & (1UL << BUTTON_USER_PIN))
        {
            if (!(LED_RED_PORT->ODR & (1UL << LED_RED_PIN)))
            {
                LED_RED_PORT->ODR |= 1UL << LED_RED_PIN;
                // USART3->TDR = 'A';
                // USART3_TX_DMA_STREAM->NDTR = npf_snprintf((char *)usart3_tx_buf, 0xFF, "Current: %u, Voltage: %u\r\n", cur_sen_adc_val, vol_sen_adc_val);
                USART3_TX_DMA_STREAM->CR |= DMA_SxCR_EN;
            }
        }
        else
        {
            LED_RED_PORT->ODR &= ~(1UL << LED_RED_PIN);
        }

        if(CUR_SEN_ADC->ISR & ADC_ISR_EOC)
        {
            CUR_SEN_ADC->ISR |= ADC_ISR_EOC;
            cur_conv_time = DESC_TIM->CNT;
        }

        // if(CUR_SEN_DMA->HISR & DMA_HISR_TCIF4)
        // {
        //     CUR_SEN_DMA->HIFCR |= DMA_HIFCR_CTCIF4;
        //     cur_tran_time = DESC_TIM->CNT;
        // }

        if(VOL_SEN_ADC->ISR & ADC_ISR_EOC)
        {
            VOL_SEN_ADC->ISR |= ADC_ISR_EOC;
            vol_conv_time = DESC_TIM->CNT;
        }

        // if(VOL_SEN_DMA->HISR & DMA_HISR_TCIF5)
        // {
        //     VOL_SEN_DMA->HIFCR |= DMA_HIFCR_CTCIF5;
        //     vol_tran_time = DESC_TIM->CNT;
        // }
    }
}

void TIM_REF_IRQHandler(void)
{
    if(TIM_REF->SR & TIM_SR_UIF)
    {
        TIM_REF->SR &= ~TIM_SR_UIF;
        
        LED_GREEN_PORT->ODR ^= 1UL << LED_GREEN_PIN;
    }
}

void CUR_SEN_ADC_IRQHandler(void)
{
    if(CUR_SEN_ADC->ISR & ADC_ISR_EOS)
    {
        CUR_SEN_ADC->ISR |= ADC_ISR_EOS;
        cur_conv_time = DESC_TIM->CNT;
    }
}

void CUR_SEN_DMA_STREAM_IRQHandler(void)
{
    if(CUR_SEN_DMA->HISR & DMA_HISR_TCIF4)
    {
        CUR_SEN_DMA->HIFCR |= DMA_HIFCR_CTCIF4;
        cur_tran_time = DESC_TIM->CNT;
    }
}

void VOL_SEN_ADC_IRQHandler(void)
{
    if(VOL_SEN_ADC->ISR & ADC_ISR_EOS)
    {
        VOL_SEN_ADC->ISR |= ADC_ISR_EOS;
        vol_conv_time = DESC_TIM->CNT;
    }
}

void VOL_SEN_DMA_STREAM_IRQHandler(void)
{
    if(VOL_SEN_DMA->HISR & DMA_HISR_TCIF5)
    {
        VOL_SEN_DMA->HIFCR |= DMA_HIFCR_CTCIF5;
        vol_tran_time = DESC_TIM->CNT;
    }
}
