#include "rcc_cfg.h"

void rcc_init(void)
{
    RCC->CR |= RCC_CR_HSEON | RCC_CR_HSEBYP;
    while(!(RCC->CR & RCC_CR_HSERDY)) __NOP();

    RCC->PLLCKSELR &= ~(RCC_PLLCKSELR_DIVM1 | RCC_PLLCKSELR_PLLSRC);
    RCC->PLLCKSELR |= RCC_PLLCKSELR_PLLSRC_HSE |
                      PLL1_M << RCC_PLLCKSELR_DIVM1_Pos;

    RCC->PLLCFGR &= ~(RCC_PLLCFGR_PLL1FRACEN | RCC_PLLCFGR_PLL1VCOSEL | RCC_PLLCFGR_PLL1RGE | RCC_PLLCFGR_DIVQ1EN | RCC_PLLCFGR_DIVR1EN);
    RCC->PLLCFGR |= RCC_PLLCFGR_PLL1RGE_1 | RCC_PLLCFGR_DIVP1EN;

    RCC->PLL1DIVR = 0x0U;
    RCC->PLL1DIVR |= ((PLL1_N - 1UL) << RCC_PLL1DIVR_N1_Pos) |
                     ((PLL1_P - 1UL) << RCC_PLL1DIVR_P1_Pos);

    RCC->D1CFGR &= ~(RCC_D1CFGR_HPRE | RCC_D1CFGR_D1PPRE | RCC_D1CFGR_D1CPRE);
    RCC->D1CFGR |= HPRE |
                   D1PPRE |
                   D1CPRE;

    RCC->D2CFGR &= ~(RCC_D2CFGR_D2PPRE1 | RCC_D2CFGR_D2PPRE2);
    RCC->D2CFGR |= D2PPRE1 |
                   D2PPRE2;

    RCC->D3CFGR &= ~(RCC_D3CFGR_D3PPRE);
    RCC->D3CFGR |= D3PPRE;

    RCC->CR |= RCC_CR_PLL1ON;
    while(!(RCC->CR & RCC_CR_PLL1RDY)) __NOP();
    RCC->CFGR &= ~RCC_CFGR_SW;
    RCC->CFGR |= RCC_CFGR_SW_PLL1;
    while((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_PLL1) __NOP();
}

void pll2_init(void)
{
    RCC->PLLCKSELR &= ~RCC_PLLCKSELR_DIVM2;
    RCC->PLLCKSELR |= PLL2_M << RCC_PLLCKSELR_DIVM2_Pos;

    RCC->PLLCFGR &= ~(RCC_PLLCFGR_PLL2FRACEN | RCC_PLLCFGR_PLL2VCOSEL | RCC_PLLCFGR_PLL2RGE | RCC_PLLCFGR_DIVQ2EN | RCC_PLLCFGR_DIVR2EN);
    RCC->PLLCFGR |= RCC_PLLCFGR_PLL2RGE_1 | RCC_PLLCFGR_DIVP2EN;

    RCC->PLL2DIVR = 0x0U;
    RCC->PLL2DIVR |= ((PLL2_N - 1UL) << RCC_PLL2DIVR_N2_Pos) |
                     ((PLL2_P - 1UL) << RCC_PLL2DIVR_P2_Pos);

    RCC->CR |= RCC_CR_PLL2ON;
    while(!(RCC->CR & RCC_CR_PLL2RDY));
}